
export const users = [
    {
        id: 'u1',
        name: 'John Doe',
        email: 'john@example.com',
        role: 'user',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    },
    {
        id: 'v1',
        name: 'Tech Gadgets Inc.',
        email: 'vendor@tech.com',
        role: 'vendor',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tech',
        rating: 4.8,
    },
    {
        id: 'a1',
        name: 'Admin User',
        email: 'admin@fyp.com',
        role: 'admin',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
    },
];

export const categories = [
    { id: 'c1', name: 'Electronics', icon: 'Cpu' },
    { id: 'c2', name: 'Fashion', icon: 'Shirt' },
    { id: 'c3', name: 'Home & Garden', icon: 'Home' },
    { id: 'c4', name: 'Sports', icon: 'Activity' },
    { id: 'c5', name: 'Books', icon: 'Book' },
];

export const products = [
    {
        id: 'p1',
        title: 'Wireless Noise Cancelling Headphones',
        price: 299.99,
        originalPrice: 349.99,
        description: 'Experience world-class noise cancellation with our premium wireless headphones. Features 30-hour battery life and exceptional sound quality.',
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
        category: 'Electronics',
        vendorId: 'v1',
        rating: 4.5,
        reviews: 128,
        stock: 50,
    },
    {
        id: 'p2',
        title: 'Smart Fitness Watch',
        price: 199.50,
        description: 'Track your health and fitness goals with this advanced smartwatch. Includes heart rate monitoring, GPS, and sleep tracking.',
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
        category: 'Electronics',
        vendorId: 'v1',
        rating: 4.2,
        reviews: 85,
        stock: 20,
    },
    {
        id: 'p3',
        title: 'Premium Cotton T-Shirt',
        price: 29.99,
        description: 'Made from 100% organic cotton, this t-shirt offers ultimate comfort and style for everyday wear.',
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
        category: 'Fashion',
        vendorId: 'v1',
        rating: 4.7,
        reviews: 210,
        stock: 100,
    },
    {
        id: 'p4',
        title: 'Modern Coffee Table',
        price: 149.00,
        originalPrice: 199.00,
        description: 'Minimalist design coffee table that fits perfectly in any modern living room. Durable and easy to assemble.',
        image: 'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=800&q=80',
        category: 'Home & Garden',
        vendorId: 'v1',
        rating: 4.0,
        reviews: 45,
        stock: 15,
    },
    {
        id: 'p5',
        title: 'Professional DSLR Camera',
        price: 1299.00,
        description: 'Capture stunning photos and videos with this professional-grade DSLR camera. Comes with a versatile lens kit.',
        image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80',
        category: 'Electronics',
        vendorId: 'v1',
        rating: 4.9,
        reviews: 320,
        stock: 5,
    },
    {
        id: 'p6',
        title: 'Running Shoes',
        price: 89.95,
        description: 'Lightweight and breathable running shoes designed for maximum performance and comfort.',
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
        category: 'Sports',
        vendorId: 'v1',
        rating: 4.6,
        reviews: 150,
        stock: 60,
    },
];

export const reviews = [
    {
        id: 'r1',
        productId: 'p1',
        userId: 'u1',
        userName: 'John Doe',
        rating: 5,
        comment: 'Amazing sound quality! Worth every penny.',
        date: '2023-10-15',
    },
    {
        id: 'r2',
        productId: 'p1',
        userId: 'u2',
        userName: 'Jane Smith',
        rating: 4,
        comment: 'Great headphones, but a bit heavy.',
        date: '2023-10-20',
    },
];
